// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RankingPreProva.Server.Data;

#nullable disable

namespace RankingPreProva.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuestaoAssunto", b =>
                {
                    b.Property<int>("AssuntosId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestoesId")
                        .HasColumnType("integer");

                    b.HasKey("AssuntosId", "QuestoesId");

                    b.HasIndex("QuestoesId");

                    b.ToTable("QuestaoAssunto");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Alternativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<char>("Letra")
                        .HasColumnType("character(1)");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId", "Letra")
                        .IsUnique();

                    b.ToTable("Alternativas");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Assunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Assuntos");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Meta")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "PRIMEIRO_PASSO",
                            Descricao = "Responda sua primeira questão.",
                            Icone = "👣",
                            Meta = 1,
                            Nome = "Primeiro Passo",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "CENTURIAO",
                            Descricao = "Responda 100 questões.",
                            Icone = "💯",
                            Meta = 100,
                            Nome = "Centurião",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "MARATONISTA",
                            Descricao = "Responda 1.000 questões.",
                            Icone = "🏃",
                            Meta = 1000,
                            Nome = "Maratonista",
                            Ordem = 3
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "CONSTANCIA",
                            Descricao = "Estude 7 dias seguidos.",
                            Icone = "🔥",
                            Meta = 7,
                            Nome = "Constância",
                            Ordem = 4
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "DISCIPLINA",
                            Descricao = "Estude 30 dias seguidos.",
                            Icone = "🛡️",
                            Meta = 30,
                            Nome = "Disciplina de Ferro",
                            Ordem = 5
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "CRIADOR",
                            Descricao = "Cadastre 10 questões.",
                            Icone = "✍️",
                            Meta = 10,
                            Nome = "Criador",
                            Ordem = 6
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "ARQUITETO",
                            Descricao = "Crie 3 provas.",
                            Icone = "🏛️",
                            Meta = 3,
                            Nome = "Arquiteto de Provas",
                            Ordem = 7
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "ESTREANTE",
                            Descricao = "Conclua sua primeira prova.",
                            Icone = "🎬",
                            Meta = 1,
                            Nome = "Estreante",
                            Ordem = 8
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "PODIO",
                            Descricao = "Fique entre os 3 primeiros no ranking de uma prova.",
                            Icone = "🏆",
                            Meta = 1,
                            Nome = "Pódio",
                            Ordem = 9
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "GABARITOU",
                            Descricao = "Acerte 100% de uma prova.",
                            Icone = "🎯",
                            Meta = 1,
                            Nome = "Gabaritou!",
                            Ordem = 10
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "ESPECIALISTA",
                            Descricao = "Acerte 50 questões do mesmo assunto.",
                            Icone = "🧠",
                            Meta = 50,
                            Nome = "Especialista",
                            Ordem = 11
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "REVISOR",
                            Descricao = "Tenha uma denúncia aceita pela moderação.",
                            Icone = "🔎",
                            Meta = 1,
                            Nome = "Revisor",
                            Ordem = 12
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "POPULAR",
                            Descricao = "Tenha uma questão ou prova com saldo de 10 votos.",
                            Icone = "⭐",
                            Meta = 10,
                            Nome = "Popular",
                            Ordem = 13
                        });
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Denuncia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlvoId")
                        .HasColumnType("integer");

                    b.Property<int>("AlvoTipo")
                        .HasColumnType("integer");

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalhe")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Motivo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutorId", "AlvoTipo", "AlvoId")
                        .IsUnique();

                    b.HasIndex("Status", "AlvoTipo", "AlvoId");

                    b.ToTable("Denuncias");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Favorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlvoId")
                        .HasColumnType("integer");

                    b.Property<int>("AlvoTipo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "AlvoTipo", "AlvoId")
                        .IsUnique();

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Prova", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.Property<string>("Banca")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ConcursoSimulado")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("NotaMinimaZero")
                        .HasColumnType("boolean");

                    b.Property<string>("Orgao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PenalidadeErro")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("PontosAcerto")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<bool>("Publica")
                        .HasColumnType("boolean");

                    b.Property<int>("Regra")
                        .HasColumnType("integer");

                    b.Property<int>("SaldoVotos")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TempoLimiteMin")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("Status", "SaldoVotos");

                    b.ToTable("Provas");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.ProvaQuestao", b =>
                {
                    b.Property<int>("ProvaId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<decimal>("Peso")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("ProvaId", "QuestaoId");

                    b.HasIndex("QuestaoId");

                    b.ToTable("ProvaQuestoes");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Questao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.Property<string>("Banca")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Concurso")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dificuldade")
                        .HasColumnType("integer");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Explicacao")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<char>("Gabarito")
                        .HasColumnType("character(1)");

                    b.Property<string>("Orgao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.Property<int>("SaldoVotos")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAcertos")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRespostas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Ano");

                    b.HasIndex("AutorId");

                    b.HasIndex("Banca");

                    b.HasIndex("Status", "SaldoVotos");

                    b.ToTable("Questoes");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.RespostaAvulsa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Correta")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<char>("Letra")
                        .HasColumnType("character(1)");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("UsuarioId", "Data");

                    b.HasIndex("UsuarioId", "QuestaoId");

                    b.ToTable("RespostasAvulsas");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.RespostaTentativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Correta")
                        .HasColumnType("boolean");

                    b.Property<char?>("Letra")
                        .HasColumnType("character(1)");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<int>("TentativaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("TentativaId");

                    b.ToTable("RespostasTentativa");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Tentativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Acertos")
                        .HasColumnType("integer");

                    b.Property<int>("DuracaoSeg")
                        .HasColumnType("integer");

                    b.Property<bool>("EhPrimeira")
                        .HasColumnType("boolean");

                    b.Property<int>("EmBranco")
                        .HasColumnType("integer");

                    b.Property<int>("Erros")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Finalizada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Iniciada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Nota")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("NotaMaxima")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ProvaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ProvaId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("IX_Tentativas_PrimeiraPorUsuario")
                        .HasFilter("\"EhPrimeira\" = true");

                    b.HasIndex("ProvaId", "EhPrimeira", "Nota");

                    b.ToTable("Tentativas");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apelido")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CargoAlvo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ConcursoAlvo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EhAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MaiorSequencia")
                        .HasColumnType("integer");

                    b.Property<int>("MetaDiaria")
                        .HasColumnType("integer");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SequenciaDias")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("UltimaAtividade")
                        .HasColumnType("date");

                    b.Property<DateTime>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Apelido")
                        .IsUnique();

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.HasIndex("Xp");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.UsuarioBadge", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ConquistadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UsuarioId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("UsuarioBadges");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlvoId")
                        .HasColumnType("integer");

                    b.Property<int>("AlvoTipo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("Valor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlvoTipo", "AlvoId");

                    b.HasIndex("UsuarioId", "AlvoTipo", "AlvoId")
                        .IsUnique();

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.XpEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Data", "UsuarioId");

                    b.ToTable("XpEventos");
                });

            modelBuilder.Entity("QuestaoAssunto", b =>
                {
                    b.HasOne("RankingPreProva.Server.Models.Assunto", null)
                        .WithMany()
                        .HasForeignKey("AssuntosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RankingPreProva.Server.Models.Questao", null)
                        .WithMany()
                        .HasForeignKey("QuestoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Alternativa", b =>
                {
                    b.HasOne("RankingPreProva.Server.Models.Questao", null)
                        .WithMany("Alternativas")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Denuncia", b =>
                {
                    b.HasOne("RankingPreProva.Server.Models.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Favorito", b =>
                {
                    b.HasOne("RankingPreProva.Server.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Prova", b =>
                {
                    b.HasOne("RankingPreProva.Server.Models.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.ProvaQuestao", b =>
                {
                    b.HasOne("RankingPreProva.Server.Models.Prova", "Prova")
                        .WithMany("Questoes")
                        .HasForeignKey("ProvaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RankingPreProva.Server.Models.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prova");

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Questao", b =>
                {
                    b.HasOne("RankingPreProva.Server.Models.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.RespostaAvulsa", b =>
                {
                    b.HasOne("RankingPreProva.Server.Models.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RankingPreProva.Server.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.RespostaTentativa", b =>
                {
                    b.HasOne("RankingPreProva.Server.Models.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RankingPreProva.Server.Models.Tentativa", null)
                        .WithMany("Respostas")
                        .HasForeignKey("TentativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Tentativa", b =>
                {
                    b.HasOne("RankingPreProva.Server.Models.Prova", "Prova")
                        .WithMany("Tentativas")
                        .HasForeignKey("ProvaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RankingPreProva.Server.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prova");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.UsuarioBadge", b =>
                {
                    b.HasOne("RankingPreProva.Server.Models.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RankingPreProva.Server.Models.Usuario", null)
                        .WithMany("Badges")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Voto", b =>
                {
                    b.HasOne("RankingPreProva.Server.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.XpEvento", b =>
                {
                    b.HasOne("RankingPreProva.Server.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Prova", b =>
                {
                    b.Navigation("Questoes");

                    b.Navigation("Tentativas");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Questao", b =>
                {
                    b.Navigation("Alternativas");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Tentativa", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("RankingPreProva.Server.Models.Usuario", b =>
                {
                    b.Navigation("Badges");
                });
#pragma warning restore 612, 618
        }
    }
}
